<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- net8.0-windows pour self-contained + PublishSingleFile -->
    <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
    <AssemblyName>SmbiosFix</AssemblyName>
    <RootNamespace>SmbiosFix</RootNamespace>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Management" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
